type "" >List2.txt
type D:\Cyberboard\BMP\CoOrds.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\ArmyTypes.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Bas\Bases.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Bat\Battalion.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Bri\ArmyBrigade.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Bri\Brigades.CFG >>List2.txt
type D:\Cyberboard\BMP\Arm\Com\Company.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Com\AS\ASCompanies.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Com\BC\BCCompanies.CFG >>List2.txt
type D:\Cyberboard\BMP\Arm\Com\GT\GTCompanies.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Com\LA\LACompanies.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Com\LI\LICompanies.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Com\RI\RICompanies.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Cor\Corps.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Div\ArmyDivision.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Div\ArmyDivisions.CFG >>List2.txt
type D:\Cyberboard\BMP\Arm\Fie\FieldArmy.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Hus\Huscarles.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Mer\Mercs.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Ran\Ranks.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Sec\Sections.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Sec\ASS\ASSections.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Sec\BCS\BCSections.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Sec\GTS\GTSections.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Sec\LAS\LASections.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Sec\LIS\LISections.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Sec\RIS\RISections.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Squ\Squads.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Squ\AS\ASSquads.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Squ\BC\BCSquads.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Squ\GT\GTSquads.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Squ\LA\LASquads.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Squ\LI\LISquads.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Squ\RI\RISquads.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Sun\Sunbursts.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Uni\Units.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Uni\ASB\Units.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Uni\BCD\Units.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Uni\GTS\Units.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Uni\LAB\Units.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Uni\LIB\Units.cfg >>List2.txt
type D:\Cyberboard\BMP\Arm\Uni\RIB\Units.cfg >>List2.txt
type D:\Cyberboard\BMP\Har\Hardware.cfg >>List2.txt
type D:\Cyberboard\BMP\Har\Cra\Craft.cfg >>List2.txt
type D:\Cyberboard\BMP\Har\Shi\Ships.cfg >>List2.txt
type D:\Cyberboard\BMP\Har\Veh\Vehicles.cfg >>List2.txt
type D:\Cyberboard\BMP\Har\Wea\Weapons.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\CoOrds.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\Marine.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MACR\MACR.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MACR\MarineACR.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MCC\MarineCC.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MCC\MarineCommandoCorps.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MCC\MCC.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MGD\MarineGD.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MGD\MGD.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MLR\MarineLR.CFG >>List2.txt
type D:\Cyberboard\BMP\Mar\MLR\MLR.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MSQ\MarineSQ.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MSQ\MSQ.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MST\MarineST.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\MST\MST.cfg >>List2.txt
type D:\Cyberboard\BMP\Mar\Ran\Ranks.cfg >>List2.txt
type D:\Cyberboard\BMP\Mer\Merchant.cfg >>List2.txt
type D:\Cyberboard\BMP\Mer\Car\Cargoes.cfg >>List2.txt
type D:\Cyberboard\BMP\Mer\Com\Companies.cfg >>List2.txt
type D:\Cyberboard\BMP\Mer\Cont\Containers.cfg >>List2.txt
type D:\Cyberboard\BMP\Mer\Haz\Hazards.cfg >>List2.txt
type D:\Cyberboard\BMP\Mer\Meg\Megacorps.cfg >>List2.txt
type D:\Cyberboard\BMP\Mer\Mod\Modules.cfg >>List2.txt
type D:\Cyberboard\BMP\Mer\Pas\Passengers.cfg >>List2.txt
type D:\Cyberboard\BMP\Mer\Ran\Ranks.cfg >>List2.txt
type D:\Cyberboard\BMP\Mer\Ter\Terms.cfg >>List2.txt
type D:\Cyberboard\BMP\Mer\UEE\UEE.cfg >>List2.txt
type D:\Cyberboard\BMP\Nav\NavyTypes.cfg >>List2.txt
type D:\Cyberboard\BMP\Nav\Bas\Bases.cfg >>List2.txt
type D:\Cyberboard\BMP\Nav\Cre\Crew.cfg >>List2.txt
type D:\Cyberboard\BMP\Nav\Dep\Departments.cfg >>List2.txt
type D:\Cyberboard\BMP\Nav\Man\Man.cfg >>List2.txt
type D:\Cyberboard\BMP\Nav\Ran\Ranks.cfg >>List2.txt
type D:\Cyberboard\BMP\Nav\Sec\NamedFleets.cfg >>List2.txt
type D:\Cyberboard\BMP\Nav\Sub\NumberedFleets.cfg >>List2.txt
type D:\Cyberboard\BMP\Nav\Sys\Squadrons.cfg >>List2.txt
type D:\Cyberboard\BMP\Nav\Typ\Types.cfg >>List2.txt
type D:\Cyberboard\BMP\Nav\USqP\Regina.cfg >>List2.txt
type D:\Cyberboard\BMP\Oth\CoOrds.cfg >>List2.txt
type D:\Cyberboard\BMP\Oth\Other.cfg >>List2.txt
type D:\Cyberboard\BMP\Oth\Bra\ColourRef.cfg >>List2.txt
type D:\Cyberboard\BMP\Oth\Lin\Box.cfg >>List2.txt
type D:\Cyberboard\BMP\Oth\Lin\Boxed.cfg >>List2.txt
type D:\Cyberboard\BMP\Oth\Lin\Boxes.cfg >>List2.txt
type D:\Cyberboard\BMP\Oth\Lin\CoOrds.cfg >>List2.txt
type D:\Cyberboard\BMP\Oth\Lin\Lines.cfg >>List2.txt
type D:\Cyberboard\BMP\Oth\Pol\CoOrds.cfg >>List2.txt
type D:\Cyberboard\BMP\Oth\Pol\Politics.cfg >>List2.txt
type D:\Cyberboard\BMP\Oth\Ran\Ranks.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\CoOrds.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Scout.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Bas\Bas.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Bra\Adm\Adm.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Bra\Com\Com.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Bra\Det\Det.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Bra\Exp\Exp.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Bra\IGS\IGS.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Bra\Ops\Ops.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Bra\Tec\Tec.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Ran\Ran.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Sta\Sta.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Sys\Sys.cfg >>List2.txt
type D:\Cyberboard\BMP\Sco\Wor\Wor.cfg >>List2.txt
type D:\Cyberboard\BMP\xSky\Cam.cfg >>List2.txt
type D:\Cyberboard\BMP\xSky\SkyRig.cfg >>List2.txt
