'CHDRIVE D:
cd D:\CYBERBOARD\
cd D:\CYBERBOARD\
annotate -f bmp\arm\armytypes.cfg -op bmp\arm\
	annotate -f BMP\Arm\Bas\Bases.cfg -op BMP\Arm\Bas\
	annotate -f BMP\Arm\Bat\Battalion.cfg -op BMP\Arm\Bat\
	annotate -f BMP\Arm\Bri\Brigades.CFG -op BMP\Arm\Bri\
	annotate -f BMP\Arm\Com\Company.cfg -op BMP\Arm\Com\
		annotate -f bmp\arm\com\as\ASCompanies.cfg -op bmp\arm\com\as\
		annotate -f bmp\arm\com\bc\BCCompanies.cfg -op bmp\arm\com\BC\
		annotate -f bmp\arm\com\GT\GTCompanies.cfg -op bmp\arm\com\GT\
		annotate -f bmp\arm\com\LA\LACompanies.cfg -op bmp\arm\com\LA\
		annotate -f bmp\arm\com\LI\LICompanies.cfg -op bmp\arm\com\LI\
		annotate -f bmp\arm\com\RI\RICompanies.cfg -op bmp\arm\com\RI\
	annotate -f BMP\Arm\Cor\Corps.cfg -op bmp\arm\cor\
	annotate -f BMP\Arm\Div\ArmyDivisions.cfg -op bmp\arm\div\
	annotate -f bmp\arm\fie\FieldArmy.cfg -op bmp\arm\fie\
	annotate -f bmp\arm\hus\huscarles.cfg -op bmp\arm\hus\
	annotate -f bmp\arm\mer\Mercs.cfg -op bmp\arm\mer\
	annotate -f bmp\arm\ran\Ranks.cfg -op bmp\arm\ran\
	annotate -f bmp\arm\sec\sections.cfg -op bmp\arm\sec\
		annotate -f bmp\arm\sec\ass\assections.cfg -op bmp\arm\sec\ass\
		annotate -f bmp\arm\sec\bcs\bcsections.cfg -op bmp\arm\sec\bcs\
		annotate -f bmp\arm\sec\gts\gtsections.cfg -op bmp\arm\sec\gts\
		annotate -f bmp\arm\sec\las\lasections.cfg -op bmp\arm\sec\las\
		annotate -f bmp\arm\sec\lis\lisections.cfg -op bmp\arm\sec\lis\
		annotate -f bmp\arm\sec\ris\risections.cfg -op bmp\arm\sec\ris\
	annotate -f bmp\arm\sun\sunbursts.cfg -op bmp\arm\sun\
	annotate -f bmp\arm\uni\units.cfg -op bmp\arm\uni\
		annotate -f bmp\arm\uni\asb\units.cfg -op bmp\arm\uni\asb\
		annotate -f bmp\arm\uni\bcd\units.cfg -op bmp\arm\uni\bcd\
		annotate -f bmp\arm\uni\gts\units.cfg -op bmp\arm\uni\gts\
		annotate -f bmp\arm\uni\lab\units.cfg -op bmp\arm\uni\lab\
		annotate -f bmp\arm\uni\lib\units.cfg -op bmp\arm\uni\lib\
		annotate -f bmp\arm\uni\rib\units.cfg -op bmp\arm\uni\rib\
	annotate -f bmp\arm\squ\squads.cfg -op bmp\arm\squ\
		annotate -f bmp\arm\squ\la\lasquads.cfg -op bmp\arm\squ\la\
		annotate -f bmp\arm\squ\li\lisquads.cfg -op bmp\arm\squ\li\
		annotate -f bmp\arm\squ\ri\risquads.cfg -op bmp\arm\squ\ri\
		annotate -f bmp\arm\squ\as\assquads.cfg -op bmp\arm\squ\as\
		annotate -f bmp\arm\squ\bc\bcsquads.cfg -op bmp\arm\squ\bc\
		annotate -f bmp\arm\squ\gt\gtsquads.cfg -op bmp\arm\squ\gt\

CD D:\CYBERBOARD\BMP\Arm"
bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Bas"
	bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Bat"
	bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Bri"
	bmptogtl
	CD  "D:\CYBERBOARD\BMP\Arm\Com"
	bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Com\RI"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Com\BC"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Com\GT"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Com\LA"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Com\LI"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Com\AS"
		bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Cor"
	bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Div"
	bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Fie"
	bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Hus"
	bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Mer"
	bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Ran"
	bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Sec"
	bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Sec\RIS"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Sec\BCS"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Sec\GTS"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Sec\LAS"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Sec\LIS"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Sec\ASS"
		bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Squ"
	bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Squ\RI"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Squ\BC"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Squ\GT"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Squ\LA"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Squ\LI"
		bmptogtl
		CD  D:\CYBERBOARD\BMP\Arm\Squ\AS"
		bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Sun"
	bmptogtl
	CD  D:\CYBERBOARD\BMP\Arm\Uni"
	bmptogtl
